---
- hosts: all
  roles:

  # osx config
  - role: dock
    apps:
    - /Applications/Safari.app
    - /Applications/Kalender.app
    - /Applications/Mail.app
    - /Applications/HipChat.app
    - /Applications/Reeder.app
    - "/Applications/iTerm.app"
    - "/Applications/Skype.app"
    folders:
    - path: ~/Applications
    - path: ~/Documents
    - path: ~/Downloads
      sort: datemodified
  - role: dashboard
    disabled: YES

  # fonts
  - role: cask_package
    tap: caskroom/fonts
    package_name: font-source-code-pro
  - role: cask_package
    tap: caskroom/fonts
    package_name: font-sauce-code-powerline

  # cli
  # shell tooling
  - role: git
    git_user_name: Alexander Schramm
    git_user_email: alexanderschramm@me.com
  - role: hub
  - role: brew_package
    package_name: vim
  - role: brew_package
    package_name: drush
  - role: brew_package
    package_name: imagemagick
  - role: brew_package
    package_name: zsh
  - role: brew_package
    package_name: autojump

  ## languages
  - role: brew_package
    package_name: node
  - role: rbenv
  - role: cask_package
    package_name: java
  - role: cask_package
    package_name: mactex
  - rubies: 
    - 1.9.3
    - 2.1.2
  - role: gem_package
    package_name: bundler

  ## databases
  - role: brew_package
    package_name: redis

  ## deployment
  - role: brew_package
    package_name: heroku-toolbelt
  # - role: brew_package
  #   package_name: ansible # Hey ! Already there !

  # gui
  ## text editors
  - role: cask_package
  - role: cask_package
    package_name: intellij-idea
  - role: cask_package
    package_name: onepassword
  ##Browsers
  - role: cask_package
    package_name: google-chrome
  - role: cask_package
    package_name: firefox
  - role: cask_package
  ##other
    package_name: graphsketcher
  - role: cask_package
    package_name: hipchat
  - role: cask_package
    package_name: instacast
  -role: cask_package
    package_name: alfred
  -role: cask_package
    package_name: sequel-pro
  -role: cask_package
    package_name: sourcetree
  -role: cask_package
    package_name: dropbox
  -role: cask_package
    package_name: google-drive
  -role: cask_package
    package_name: tunnelblick
  -role: cask_package
    package_name: little_snitch
  -role: cask_package
    package_name: synology-cloud-station
  -role: cask_package
    package_name: synology-photo-station-uploader
  -role: cask_package
    package_name: synology-assistant
  -role: cask_package
    package_name: postgres
  -role: cask_package
    package_name: skype
  -role: cask_package
    package_name: spotify
  -role: cask_package
    package_name: steam
  -role: cask_package
    package_name: subler
  -role: cask_package
    package_name: the-unarchiver
  -role: cask_package
    package_name: zotero
  - role: cask_package
    package_name: spectacle
  - role: alfred
